library(RPostgreSQL)
library(ROCR)

con = dbConnect(PostgreSQL(), user= "w10403323", password="terence", dbname="mimiciii")

text="12"


train_table = dbGetQuery(con, statement = paste("Select death_inhosp, age, Case When gender = 'F' then 0 else 1 end as gender,
                                                 first_sapsii, lda_50_",text," 
                                                 from aggregate_matrix
                                                 where train = 1 and staytime > ", text, ";", sep = ""))

test_table = dbGetQuery(con, statement = paste("Select death_inhosp, age, Case When gender = 'F' then 0 else 1 end as gender,
                                                 first_sapsii, lda_50_",text," 
                                               from aggregate_matrix
                                               where train = 0 and staytime > ", text, " and lda_50_"
                                               ,text," not like 'No notes';", sep = ""))

death = as.numeric(train_table$death_inhosp)
age = train_table$age
gender = as.numeric(train_table$gender)
first_sapsii = as.numeric(train_table$first_sapsii)

text_data = as.data.frame(strsplit(train_table[,5], " "))
lda_01 = as.numeric(as.character(text_data[ 1,]))
lda_02 = as.numeric(as.character(text_data[ 2,]))
lda_03 = as.numeric(as.character(text_data[ 3,]))
lda_04 = as.numeric(as.character(text_data[ 4,]))
lda_05 = as.numeric(as.character(text_data[ 5,]))
lda_06 = as.numeric(as.character(text_data[ 6,]))
lda_07 = as.numeric(as.character(text_data[ 7,]))
lda_08 = as.numeric(as.character(text_data[ 8,]))
lda_09 = as.numeric(as.character(text_data[ 9,]))
lda_10 = as.numeric(as.character(text_data[10,]))
lda_11 = as.numeric(as.character(text_data[11,]))
lda_12 = as.numeric(as.character(text_data[12,]))
lda_13 = as.numeric(as.character(text_data[13,]))
lda_14 = as.numeric(as.character(text_data[14,]))
lda_15 = as.numeric(as.character(text_data[15,]))
lda_16 = as.numeric(as.character(text_data[16,]))
lda_17 = as.numeric(as.character(text_data[17,]))
lda_18 = as.numeric(as.character(text_data[18,]))
lda_19 = as.numeric(as.character(text_data[19,]))
lda_20 = as.numeric(as.character(text_data[20,]))
lda_21 = as.numeric(as.character(text_data[21,]))
lda_22 = as.numeric(as.character(text_data[22,]))
lda_23 = as.numeric(as.character(text_data[23,]))
lda_24 = as.numeric(as.character(text_data[24,]))
lda_25 = as.numeric(as.character(text_data[25,]))
lda_26 = as.numeric(as.character(text_data[26,]))
lda_27 = as.numeric(as.character(text_data[27,]))
lda_28 = as.numeric(as.character(text_data[28,]))
lda_29 = as.numeric(as.character(text_data[29,]))
lda_30 = as.numeric(as.character(text_data[30,]))
lda_31 = as.numeric(as.character(text_data[31,]))
lda_32 = as.numeric(as.character(text_data[32,]))
lda_33 = as.numeric(as.character(text_data[33,]))
lda_34 = as.numeric(as.character(text_data[34,]))
lda_35 = as.numeric(as.character(text_data[35,]))
lda_36 = as.numeric(as.character(text_data[36,]))
lda_37 = as.numeric(as.character(text_data[37,]))
lda_38 = as.numeric(as.character(text_data[38,]))
lda_39 = as.numeric(as.character(text_data[39,]))
lda_40 = as.numeric(as.character(text_data[40,]))
lda_41 = as.numeric(as.character(text_data[41,]))
lda_42 = as.numeric(as.character(text_data[42,]))
lda_43 = as.numeric(as.character(text_data[43,]))
lda_44 = as.numeric(as.character(text_data[44,]))
lda_45 = as.numeric(as.character(text_data[45,]))
lda_46 = as.numeric(as.character(text_data[46,]))
lda_47 = as.numeric(as.character(text_data[47,]))
lda_48 = as.numeric(as.character(text_data[48,]))
lda_49 = as.numeric(as.character(text_data[49,]))
lda_50 = as.numeric(as.character(text_data[50,]))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
train_data = as.data.frame(cbind(death, age, gender, first_sapsii, lda_01, lda_02, lda_03, lda_04, lda_05, lda_06, lda_07, lda_08, lda_09, lda_10, lda_11, lda_12, lda_13, lda_14, lda_15, lda_16, lda_17, lda_18, lda_19, lda_20, lda_21, lda_22, lda_23, lda_24, lda_25, lda_26, lda_27, lda_28, lda_29, lda_30, lda_31, lda_32, lda_33, lda_34, lda_35, lda_36, lda_37, lda_38, lda_39, lda_40, lda_41, lda_42, lda_43, lda_44, lda_45, lda_46, lda_47, lda_48, lda_49, lda_50))
#train_data = as.data.frame(cbind(death, age, gender, first_sapsii))



death = as.numeric(test_table$death_inhosp)
age = test_table$age
gender = as.numeric(test_table$gender)
first_sapsii = as.numeric(test_table$first_sapsii)

text_data = as.data.frame(strsplit(test_table[,5], " "))
lda_01 = as.numeric(as.character(text_data[ 1,]))
lda_02 = as.numeric(as.character(text_data[ 2,]))
lda_03 = as.numeric(as.character(text_data[ 3,]))
lda_04 = as.numeric(as.character(text_data[ 4,]))
lda_05 = as.numeric(as.character(text_data[ 5,]))
lda_06 = as.numeric(as.character(text_data[ 6,]))
lda_07 = as.numeric(as.character(text_data[ 7,]))
lda_08 = as.numeric(as.character(text_data[ 8,]))
lda_09 = as.numeric(as.character(text_data[ 9,]))
lda_10 = as.numeric(as.character(text_data[10,]))
lda_11 = as.numeric(as.character(text_data[11,]))
lda_12 = as.numeric(as.character(text_data[12,]))
lda_13 = as.numeric(as.character(text_data[13,]))
lda_14 = as.numeric(as.character(text_data[14,]))
lda_15 = as.numeric(as.character(text_data[15,]))
lda_16 = as.numeric(as.character(text_data[16,]))
lda_17 = as.numeric(as.character(text_data[17,]))
lda_18 = as.numeric(as.character(text_data[18,]))
lda_19 = as.numeric(as.character(text_data[19,]))
lda_20 = as.numeric(as.character(text_data[20,]))
lda_21 = as.numeric(as.character(text_data[21,]))
lda_22 = as.numeric(as.character(text_data[22,]))
lda_23 = as.numeric(as.character(text_data[23,]))
lda_24 = as.numeric(as.character(text_data[24,]))
lda_25 = as.numeric(as.character(text_data[25,]))
lda_26 = as.numeric(as.character(text_data[26,]))
lda_27 = as.numeric(as.character(text_data[27,]))
lda_28 = as.numeric(as.character(text_data[28,]))
lda_29 = as.numeric(as.character(text_data[29,]))
lda_30 = as.numeric(as.character(text_data[30,]))
lda_31 = as.numeric(as.character(text_data[31,]))
lda_32 = as.numeric(as.character(text_data[32,]))
lda_33 = as.numeric(as.character(text_data[33,]))
lda_34 = as.numeric(as.character(text_data[34,]))
lda_35 = as.numeric(as.character(text_data[35,]))
lda_36 = as.numeric(as.character(text_data[36,]))
lda_37 = as.numeric(as.character(text_data[37,]))
lda_38 = as.numeric(as.character(text_data[38,]))
lda_39 = as.numeric(as.character(text_data[39,]))
lda_40 = as.numeric(as.character(text_data[40,]))
lda_41 = as.numeric(as.character(text_data[41,]))
lda_42 = as.numeric(as.character(text_data[42,]))
lda_43 = as.numeric(as.character(text_data[43,]))
lda_44 = as.numeric(as.character(text_data[44,]))
lda_45 = as.numeric(as.character(text_data[45,]))
lda_46 = as.numeric(as.character(text_data[46,]))
lda_47 = as.numeric(as.character(text_data[47,]))
lda_48 = as.numeric(as.character(text_data[48,]))
lda_49 = as.numeric(as.character(text_data[49,]))
lda_50 = as.numeric(as.character(text_data[50,]))

test_data = as.data.frame(cbind(death, age, gender, first_sapsii, lda_01, lda_02, lda_03, lda_04, lda_05, lda_06, lda_07, lda_08, lda_09, lda_10, lda_11, lda_12, lda_13, lda_14, lda_15, lda_16, lda_17, lda_18, lda_19, lda_20, lda_21, lda_22, lda_23, lda_24, lda_25, lda_26, lda_27, lda_28, lda_29, lda_30, lda_31, lda_32, lda_33, lda_34, lda_35, lda_36, lda_37, lda_38, lda_39, lda_40, lda_41, lda_42, lda_43, lda_44, lda_45, lda_46, lda_47, lda_48, lda_49, lda_50))
#test_data = as.data.frame(cbind(death, age, gender, first_sapsii))

log_model=glm(death ~.,family=binomial(link='logit'),data=train_data[,c(1:4)])
prediction = predict(log_model,test_data, type='response')
pred <- prediction( prediction, test_data$death)
perf <- performance(pred,"tpr","fpr")
plot(perf)
AUC=unlist(slot(performance(pred,"auc"), "y.values"));AUC
perf1 <- performance(pred, "sens", "spec")
plot(perf1)
